# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-14 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Contact',
        ),
    ]
